### ISSUE TITLE
Windows Runner Experiencing Issues

### ISSUE THREAD

**Issue by ChristopherDavenport** [olafurpg/setup-scala#32]
```
- uses: olafurpg/setup-scala@v10
os:  windows-latest
```

```
Run olafurpg/setup-scala@v10
Installing Java version 'adopt@1.8'
Install Java
  exec curl -sL -o C:\Users\runneradmin\bin\jabba.exe https://github.com/shyiko/jabba/releases/download/0.11.2/jabba-0.11.2-windows-amd64.exe { silent: true }
  chmod 755 C:\Users\runneradmin\bin\jabba.exe
  exec C:\Users\runneradmin\bin\jabba.exe ls-remote
  The system cannot execute the specified program.
  Error: exec: The system cannot execute the specified program.
  ```

**Comment by olafurpg** [comment]
Thank you for reporting! We have been using this project together with Windows in the Metals repo without issues https://github.com/scalameta/metals/blob/6fd19300ed684410875db340e329cb85a42c58f2/.github/workflows/ci.yml#L14

You can try to remove setup-scala since `sbt` is actually provided out of the box with GitHub Actions now. This project is only needed if you want to test multiple JVM versions.
